### ISSUE TITLE
Downloaded File default permissions.

### ISSUE THREAD

**Issue by Healzangels** [ryakel/sonarr-yt-dlp#34]
Hey, sorry if two issues is more annoying than just including everything in one. Let me know and I can certain just add this to the old one or if this is better certainly leave it! 

The 2nd issue I'm currently having is with the permissions the file that is downloaded have compared to other applications especially the permissions of Sonarr. Currently files downloaded with Sonarr are set with permissions  -rw-rw-r--
 while files that come from ytdl are set to be: -rw-r--r--
This unfortunately prevents sonarr from having access to rename these files.

Can provide any additional logs, details etc that you may need. 

Thanks again!

**Comment by ryakel** [comment]
@Healzangels I can replicate the permissions you are discussing for files downlaoded wiith yt-dlp, but my sonarr container has no issues renaming files. Can you tell me a little about your setup? Specifically:

- How are you running sonarr?
   -  Is it on the same host? 
   - Docker or full app install?
- Is docker running as root or reduced permissions?

I will have more clarification questions once I get answers to those.

**Comment by Healzangels** [comment]
Thanks for the follow up! 
Additional info: 
System OS: unraid 6.12.6

Running Sonarr via docker on the same host as sonarr-yt-dlp.
AFAIK I've not made any changes to docker running as root/reduced permissions running default setting unraid's docker config provides.

Sonarr container isn't running as Privileged nor is sonarr-yt-dlp. 
Including screenshots of the permissions section of my Sonarr setup as well as the PUID/PGID/UMASK that the docker template is using.
![SonarrPermissions](https://github.com/ryakel/sonarr-yt-dlp/assets/47136415/da2361f5-280a-4853-89b0-200174eb0bb6)
![PUID](https://github.com/ryakel/sonarr-yt-dlp/assets/47136415/4ff729a2-8b0d-44c4-92e4-4e3c67189990)

Also Sonarr is able to detect/see the files. If Refresh/Scan it will come right up. 

From Sonarr Log if I try to rename/delete a file generated by sonarr-yt-dlp
` ---> System.IO.IOException: Permission denied`

I'm sure I could have a permissions issue being introduced here somewhere as permissions is one place I'm not overly comfortable in. But at least thus far this is first thing I've seen where Sonarr runs into a permissions issue. 

Thanks

**Comment by Healzangels** [comment]
Also since I'm running on unraid/enjoy having icon for my containers so made this, figured I share!
![sonarr-yt-dl](https://github.com/ryakel/sonarr-yt-dlp/assets/47136415/bd5ac1f3-35b0-4183-9ae3-c31d86771a14)

**Comment by ryakel** [comment]
Sounds like there may be a mismatch in your container configs. Can you confirm that your PUID/GUID/UMASK are the same settings for both Sonarr and Sonarr_ytdlp containers?

Found this old Reddit thread that talks about this too. https://www.reddit.com/r/unRAID/comments/hl3s68/folder_permissions_docker_pgid_puid_umask/

Let me know if that works. 

Love the logo! You ok if I add it to the readme with attribution?

**Comment by Healzangels** [comment]
Glad you like it! Logos all yours to use.

So gave that a shot, I've made my containers match as far as the PUID/GUID/UMASK variable goes.
Included a screenshot, on the left is sonarr-yt-dlp and right sonarr.

![SidebySide](https://github.com/ryakel/sonarr-yt-dlp/assets/47136415/139baaf6-4233-443f-926d-45fbbc50400c)

Did a quick test and seems to be no change. Deleted a previously downloaded file, updated in sonarr, allowed s-yt-dlp to re-dl but still seeing the file permissions as -rw-r--r-- and permission denied. 

I had actually been doing a little digging in on PUID/GUID as struck me maybe that was the culprit/key. 

Came across this unraid forum post that mentioned "[PGID and PUID have to be supported by the container](https://forums.unraid.net/topic/118751-puid-pgid-and-umask/?do=findComment&comment=1255753)" 

I know I've seen some containers/templates that don't include this so got me thinking maybe it was something like that? 

Thanks again for all the help!

**Comment by ryakel** [comment]
@Healzangels After some additional digging, I am fairly convinced that being able set PUID/PGID/UMASK in the compose file or on the container will get you there. 

I’m going to explore either switching over to [linuxserver.io’s base alpine image](https://github.com/linuxserver/docker-baseimage-alpine) or integrating [s6-overlay](https://github.com/just-containers/s6-overlay) into my existing build. 

As a short path, I will probably try the former in a feature branch and have you give it a go. If that works, I can work out a rational path. I should be able to have this done in a few days or so.

**Comment by Healzangels** [comment]
Sounds good, I'll do some additional testing with setting on the template/unraid container gui (like the screenshots) and as well with docker compose. 

Thanks again!

**Comment by Healzangels** [comment]
Did some additional testing, unfortunately no positive results so far. 

Additional searching and found mention of setting UMASK to 000 for unraid docker container since:
UMASK=022 is chmod 755
UMASK=002 is chmod 775
UMASK=000 is chmod 777 
But no luck. Also gave this a try with just UMASK 000 no PUID/PGID, same results.

Decided maybe it was something about the template so decided to give same tests a try with docker compose but again same results with same tests.

This was the docker compose file I had used,

```
version: "3.4"
services:
  sonarr-yt-dlp-compose:
    image: ryakel/sonarr-yt-dlp:dev
    container_name: sonarr-yt-dlp-compose
    network_mode: dockerproxy
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
    volumes:
      - /mnt/cache/appdata/sonarr-yt-dlp/logs/:/logs
      - /mnt/cache/appdata/sonarr-yt-dlp/:/config
      - /mnt/user/:/sonarr_root
    restart: unless-stopped
```
I'll continue to do some digging on if there is another method I can try to set PUID/PGID/UMASK.

-Cheers!

**Comment by ryakel** [comment]
@Healzangels 

I've made some adjustments to a branch to respect environment variables for UID and GID. I've confirmed the container should be running UMASK of `002`. Give this compose file run and see if it sorts you out. Note that the image tag is `test` and not `dev`. 

```
version: "3.4"
services:
  sonarr-yt-dlp-compose:
    image: ryakel/sonarr-yt-dlp:test
    container_name: sonarr-yt-dlp-compose
    network_mode: dockerproxy
    environment:
      - UID=99
      - GID=100
    volumes:
      - /mnt/cache/appdata/sonarr-yt-dlp/logs/:/logs
      - /mnt/cache/appdata/sonarr-yt-dlp/:/config
      - /mnt/user/:/sonarr_root
    restart: unless-stopped
```
